let data = [
{
    id : 1,
    image: "/images/Bata.jpg",
    title : "Bata",
    type : "Shoes",
    price : 600,
    totalquantity : 20,
},
{
    id : 2,
    image: "/images/campus.jpg",
    title : "Campus",
    type : "Shoes",
    price : 800,
    totalquantity : 40,
},
{
    id : 3,
    image: "/images/puma.jpg",
    title : "Puma",
    type : "Shoes",
    price : 700,
    totalquantity : 60,
},
{
    id : 4,
    image: "/images/shirtmen.jpg",
    title : "Shirt 1",
    type : "shirt",
    price : 200,
    totalquantity : 70,
},
{
    id: 5,
    image: "/images/shoes.jpg",
    title : "Adidas",
    type : "Shoes",
    price : "Rs 1000",
    totalquantity : 80,
},
{
    id: 6,
    image: "/images/shoes2.jpg",
    title : " Nike ",
    type : "Shoes",
    price : 200,
    totalquantity : 90,
},
{
    id: 7,
    image: "/images/Bata.jpg",
    title : "Bata",
    type : "Shoes",
    price : 600,
    totalquantity : 30,
},
{
    id: 8,
    image: "/images/campus.jpg",
    title : "Campus",
    type : "Shoes",
    price : 800,
    totalquantity : 100,
},
{   
    id : 9,
    image: "/images/puma.jpg",
    title : "Puma",
    type : "Shoes",
    price : 700,
    totalquantity :120,
},
{
    id : 10,
    image: "/images/shirtmen.jpg",
    title : "Shirt 1",
    type : "shirt",
    price :200,
    totalquantity : 120,
},
{
    id : 11,
    image: "/images/shoes.jpg",
    title : "Adidas",
    type : "Shoes",
    price : 1000,
    totalquantity : 40,
},
{
    id : 12,
    image: "/images/shoes2.jpg",
    title : " Nike ",
    type : "Shoes",
    price : 200,
    totalquantity : 20,
},


]
export default data;